#!/bin/sh
# Sinh lại Formula/hellopay.rb từ checksums.txt của một bản phát hành.
#
#   scripts/update-formula.sh v0.1.0 ../homebrew-tap/Formula/hellopay.rb
#
# Vì sao cần script này: GoReleaser chỉ còn sinh **cask** một cách chính thức
# (mục `homebrew_casks`). Mục `brews` sinh formula vẫn chạy nhưng đã deprecated —
# `goreleaser check` fail và nó có thể biến mất ở bản sau. Script này tự dựng
# formula nên không phụ thuộc vào mục đó. Nó ghi đè toàn bộ file thay vì sed từng
# dòng: sed dễ khớp sai và để lại file nửa cũ nửa mới.
set -eu

REPO="hoanghuydev/hellopay"
BIN="hellopay"
CLASS="Hellopay"          # tên class Ruby: hellopay -> Hellopay
DESC="A fake CLI for practising releases"
LICENSE="MIT"

version="${1:-}"
out="${2:-../homebrew-tap/Formula/$BIN.rb}"
[ -n "$version" ] || { echo "Usage: $0 <version> [output-file]" >&2; exit 1; }

tag="v${version#v}"
num="${tag#v}"

# HELLOPAY_CHECKSUMS trỏ tới file cục bộ — dùng khi thử trước lúc phát hành.
if [ -n "${HELLOPAY_CHECKSUMS:-}" ]; then
  sums=$(cat "$HELLOPAY_CHECKSUMS")
else
  url="https://github.com/$REPO/releases/download/$tag/checksums.txt"
  sums=$(curl -fsSL "$url") || { echo "Error: could not download $url" >&2; exit 1; }
fi

# Lấy mã băm của một gói. Hàm này chạy trong $(...) nên `exit` của nó chỉ thoát
# subshell — vì thế nó trả về chuỗi rỗng và người gọi phải tự kiểm. Gán vào biến
# trước khi dựng file: với `set -e`, gán từ lệnh thất bại sẽ dừng cả script.
sha_of() {
  printf '%s\n' "$sums" | sed -n "s/^\([a-f0-9]\{64\}\)  *${BIN}_${num}_$1\.tar\.gz\$/\1/p"
}

require_sha() {
  s=$(sha_of "$1")
  [ -n "$s" ] || { echo "Error: checksum entry not found for ${BIN}_${num}_$1.tar.gz" >&2; return 1; }
  printf '%s' "$s"
}

# Lấy đủ 4 mã băm TRƯỚC khi ghi file. Thiếu một cái là dừng ngay — thà không có
# formula còn hơn có formula với sha256 rỗng, vì file rỗng vẫn push lên tap được
# và làm mọi người cài lỗi.
sha_darwin_arm64=$(require_sha darwin_arm64)
sha_darwin_amd64=$(require_sha darwin_amd64)
sha_linux_arm64=$(require_sha linux_arm64)
sha_linux_amd64=$(require_sha linux_amd64)

# Ghi ra file tạm rồi mới thay thế, để lỗi giữa đường không để lại formula dở dang.
mkdir -p "$(dirname "$out")"
tmp_out="$out.tmp.$$"
trap 'rm -f "$tmp_out"' EXIT INT TERM

cat > "$tmp_out" <<EOF
# This file is generated by scripts/update-formula.sh. DO NOT EDIT.
class $CLASS < Formula
  desc "$DESC"
  homepage "https://github.com/$REPO"
  version "$num"
  license "$LICENSE"

  on_macos do
    on_arm do
      url "https://github.com/$REPO/releases/download/$tag/${BIN}_${num}_darwin_arm64.tar.gz"
      sha256 "$sha_darwin_arm64"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/$tag/${BIN}_${num}_darwin_amd64.tar.gz"
      sha256 "$sha_darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/$REPO/releases/download/$tag/${BIN}_${num}_linux_arm64.tar.gz"
      sha256 "$sha_linux_arm64"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/$tag/${BIN}_${num}_linux_amd64.tar.gz"
      sha256 "$sha_linux_amd64"
    end
  end

  def install
    bin.install "$BIN"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/$BIN version")
  end
end
EOF

mv "$tmp_out" "$out"
echo "Wrote $out for $tag"
